version: '2'
services:
  web:
    image: nginx_web
    build:
      context: ./server
      dockerfile: Dockerfile
    networks:
      - zyx
  proxy:
    image: nginx_proxy
    build:
      context: ./proxy
      dockerfile: Dockerfile
    volumes:
      - proxy:/tmp
    networks:
      - zyx
    ports:
      - "5000:80"
networks:
  zyx:
volumes:
    proxy:
